# Generated by Django 6.0 on 2026-01-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='choice_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='blog.blog'),
        ),
    ]
