# Generated by Django 6.0 on 2026-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reviews_choice_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='blog',
            name='url_blog',
            field=models.URLField(null=True, verbose_name='Enter pyur link'),
        ),
    ]
